import test from 'node:test';import assert from 'node:assert/strict';
import {validatePlan,compilePlan} from './federation.mjs';
function fixture(){return {type:'FeatureCollection',schema:'ventus.build-plan.v1',metadata:{purpose:'fixture'},features:Array.from({length:100},(_,i)=>({type:'Feature',id:'B'+i,geometry:null,properties:{app:i<50?'gridatlas':'pipelinenews',title:'Build '+i,ownerRepository:'Ventusltd/testcode',modulePath:'cartridges/build-'+i+'.mjs',dependsOn:i?['B'+(i-1)]:[],sourceFeeds:['source:fixture'],status:'planned',generation:null,change:'One meaningful change',acceptance:{local:'semantic fixture',chrome:'real browser',ci:'exact commit',deployed:'served hash'},evidence:[],rollback:'Previous pinned release'}}))};}
test('valid100plan compiles deterministic null-geometry positional graph with proof scope',()=>{const p=fixture(),before=JSON.stringify(p);assert.equal(validatePlan(p).ok,true);const a=compilePlan(p),b=compilePlan(p);assert.deepEqual(a,b);assert.equal(JSON.stringify(p),before);assert.ok(a.nodes.features.every(f=>f.geometry===null&&f.properties.status==='planned'));assert.equal(a.edges.edge_format,'index-array-v1');assert.ok(a.edges.edges.every(e=>Number.isInteger(e[0])&&Number.isInteger(e[1])&&a.nodes.features[e[0]]&&a.nodes.features[e[1]]));assert.equal(a.manifest.schema_version,'atlas-cartridge-v0.2');assert.match(a.manifest.provenance.planSha256,/^[a-f0-9]{64}$/);assert.ok(a.evidence.records.every(e=>e.classification==='declared_plan'));});
test('canonical digest ignores object key order but binds changed plan content',()=>{const p=fixture(),q={features:p.features,metadata:p.metadata,schema:p.schema,type:p.type};assert.equal(compilePlan(p).manifest.provenance.planSha256,compilePlan(q).manifest.provenance.planSha256);q.metadata={purpose:'different'};assert.notEqual(compilePlan(p).manifest.provenance.planSha256,compilePlan(q).manifest.provenance.planSha256);});
test('duplicate dangling cyclic and self dependencies fail closed',()=>{for(const mutate of [p=>p.features[1].id='B0',p=>p.features[0].properties.dependsOn=['missing'],p=>p.features[0].properties.dependsOn=['B99'],p=>p.features[0].properties.dependsOn=['B0']]){const p=fixture();mutate(p);assert.equal(validatePlan(p).ok,false);assert.throws(()=>compilePlan(p));}});
test('unsafe module paths, fake completion and invented geography are rejected',()=>{for(const mutate of [p=>p.features[0].properties.modulePath='../escape',p=>p.features[0].properties.modulePath='a/%2e%2e/b',p=>p.features[0].properties.modulePath='C:/x',p=>p.features[0].properties.status='accepted',p=>p.features[0].properties.generation='202609052040',p=>p.features[0].geometry={type:'Point',coordinates:[0,0]}]){const p=fixture();mutate(p);assert.equal(validatePlan(p).ok,false);}});
test('counts and required acceptance contracts cannot be omitted',()=>{for(const mutate of [p=>p.features.pop(),p=>p.features[50].properties.app='gridatlas',p=>delete p.features[0].properties.acceptance.chrome,p=>p.features[0].properties.sourceFeeds=['duplicate','duplicate']]){const p=fixture();mutate(p);assert.equal(validatePlan(p).ok,false);}});

function migration(){return {sourceRepository:'Ventusltd/globalgrid2050',sourceCommit:'a'.repeat(40),destinationRepository:'Ventusltd/testcode',destinationPath:'pipelines/feed.py',transferStatus:'blocked_pending_dependency_audit',files:[{path:'.github/workflows/feed.yml',sha256:'b'.repeat(64),kind:'workflow'},{path:'scripts/feed.py',sha256:'c'.repeat(64),kind:'script'}],dependencies:[{from:'.github/workflows/feed.yml',to:'scripts/feed.py',type:'runs_script',evidence:'.github/workflows/feed.yml:20'}]};}
test('migration graph retains pinned workflow-script relationship and blocked destination as metadata',()=>{const p=fixture();p.features[0].properties.migration=migration();const result=compilePlan(p),r=result.evidence.records.find(e=>e.kind==='runs_script');assert.equal(r.classification,'declared_from_source');assert.equal(r.sourceCommit,'a'.repeat(40));assert.ok(result.nodes.features.some(f=>f.properties.repo_type==='workflow'));assert.ok(result.edges.edges.some(e=>e[2]==='planned_destination'));assert.deepEqual(result.evidence.sourceEvidence[0].migration,p.features[0].properties.migration);result.evidence.sourceEvidence[0].migration.transferStatus='changed';assert.equal(p.features[0].properties.migration.transferStatus,'blocked_pending_dependency_audit');});
test('migration rejects unknown owner, short pin, unsafe paths, unresolved dependency or claimed transfer',()=>{for(const mutate of [m=>m.destinationRepository='Ventusltd/unassigned',m=>m.sourceCommit='main',m=>m.files[0].path='../escape',m=>m.dependencies[0].to='missing.py',m=>m.transferStatus='completed']){const p=fixture();p.features[0].properties.migration=migration();mutate(p.features[0].properties.migration);assert.equal(validatePlan(p).ok,false);}});

test('same pinned source file cannot acquire conflicting hashes across builds',()=>{const p=fixture();p.features[0].properties.migration=migration();p.features[1].properties.migration=migration();p.features[1].properties.migration.files[0].sha256='d'.repeat(64);assert.equal(validatePlan(p).ok,false);});

test('shared workflow-script relation is a single graph edge with separate build citations',()=>{const p=fixture();p.features[0].properties.migration=migration();p.features[1].properties.migration=migration();const result=compilePlan(p);assert.equal(result.edges.edges.filter(e=>e[2]==='runs_script').length,1);assert.equal(result.evidence.records.filter(e=>e.kind==='runs_script').length,2);assert.equal(new Set(result.edges.edges.map(JSON.stringify)).size,result.edges.edges.length);assert.ok(result.nodes.features.every(f=>f.properties.rag==='grey'&&f.properties.status==='planned'));});
